{
  config,
  lib,
  pkgs,
  inputs ? {},
  ...
}: {
  options.dev-config.tmux = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable dev-config tmux setup";
    };

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.tmux;
      description = "Tmux package to use";
    };

    # NOTE: there is intentionally no `configSource` option. All tmux config is
    # generated by `programs.tmux.extraConfig` below (the single source of
    # truth). The repo's tmux/tmux.conf is a non-consumed reference stub.

    gitmuxConfigSource = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default =
        if inputs ? dev-config
        then "${inputs.dev-config}/tmux/gitmux.conf"
        else null;
      description = "Path to gitmux configuration file";
      example = lib.literalExpression ''"''${inputs.dev-config}/tmux/gitmux.conf"'';
    };

    devpodConnect = {
      enable = lib.mkEnableOption "DevPod tmux integration (Tailscale-based)";

      connectScriptSource = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default =
          if inputs ? dev-config
          then "${inputs.dev-config}/tmux/scripts/devpod-connect.sh"
          else null;
        description = "Path to DevPod connect script";
      };

      statusScriptSource = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default =
          if inputs ? dev-config
          then "${inputs.dev-config}/tmux/scripts/devpod-status.sh"
          else null;
        description = "Path to DevPod status bar script";
      };

      mutagenHookScriptSource = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default =
          if inputs ? dev-config
          then "${inputs.dev-config}/tmux/scripts/devpod-mutagen-hook.sh"
          else null;
        description = "Path to Mutagen auto-sync hook script for DevPod sessions";
      };

      bootstrapScriptSource = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default =
          if inputs ? dev-config
          then "${inputs.dev-config}/tmux/scripts/devpod-bootstrap.sh"
          else null;
        description = "Path to DevPod bootstrap script that auto-creates sessions on tmux start";
      };
    };

    # Declarative options mirrored into programs.tmux below
    prefix = lib.mkOption {
      type = lib.types.str;
      default = "C-a";
      description = "Tmux prefix key";
    };

    baseIndex = lib.mkOption {
      type = lib.types.int;
      default = 1;
      description = "Base index for windows and panes";
    };

    mouse = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Enable mouse support";
    };

    historyLimit = lib.mkOption {
      type = lib.types.int;
      default = 10000;
      description = "Scrollback buffer size";
    };
  };

  config = lib.mkIf config.dev-config.tmux.enable {
    programs.tmux = {
      enable = true;
      package = config.dev-config.tmux.package;
      prefix = config.dev-config.tmux.prefix;
      baseIndex = config.dev-config.tmux.baseIndex;
      mouse = config.dev-config.tmux.mouse;
      historyLimit = config.dev-config.tmux.historyLimit;
      terminal = "tmux-256color";
      keyMode = "vi";
      escapeTime = 0;
      aggressiveResize = true;
      focusEvents = true;

      # Install tmux plugins via Nix (replaces TPM)
      #
      # Catppuccin v2 (catppuccin/tmux >= 2.x) reads its @catppuccin_* options at
      # *source time*, so they must be set BEFORE the plugin's run-shell. Home
      # Manager emits a plugin attrset's `extraConfig` immediately before that
      # plugin's run-shell, which gives us the required ordering. It must also
      # load before any other plugin that touches the status line, hence its
      # position ahead of resurrect/continuum/battery/cpu below.
      plugins = with pkgs.tmuxPlugins; [
        sensible # tmux-sensible
        {
          plugin = catppuccin; # catppuccin/tmux v2 (full status-line theme)
          extraConfig = ''
            set -g @catppuccin_flavor 'mocha'

            # Window list: rounded tabs showing index + name
            set -g @catppuccin_window_status_style 'rounded'
            set -g @catppuccin_window_number_position 'left'
            set -g @catppuccin_window_text ' #W'
            set -g @catppuccin_window_current_text ' #W'
            # The plugin sets status-style itself (off @catppuccin_status_background),
            # so we do not set it here — @thm_* vars don't exist until it sources.
          '';
        }
        resurrect # tmux-resurrect (save/restore sessions)
        continuum # tmux-continuum (auto-save)
        battery # tmux-battery (battery status)
        cpu # tmux-cpu (CPU/RAM status)
        vim-tmux-navigator # christoomey/vim-tmux-navigator
        yank # tmux-yank (clipboard integration)
        tmux-fzf # sainnhe/tmux-fzf (fuzzy finder)
      ];

      # Single source of truth for all tmux config (the repo's tmux/tmux.conf
      # is a non-consumed reference stub; do not symlink it).
      extraConfig =
        ''
          # Terminal settings
          set -as terminal-overrides ",*:Tc"
          set -as terminal-features ",*:hyperlinks"
          set -g allow-passthrough on
          set -ga update-environment TERM
          set -ga update-environment TERM_PROGRAM

          # Use login shell (inherits from environment)
          set -g default-command "''${SHELL}"

          # Window/pane settings
          setw -g pane-base-index 1
          set -g renumber-windows on
          set -g repeat-time 300

          # -------------------------------------------------------------------
          # Key Bindings
          # -------------------------------------------------------------------

          # Quick configuration reload
          bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf reloaded!"

          # Split panes using | and - (more intuitive)
          bind | split-window -h -c "#{pane_current_path}"
          bind - split-window -v -c "#{pane_current_path}"
          unbind '"'
          unbind %

          # Resize panes with Vim keys
          bind -r H resize-pane -L 5
          bind -r J resize-pane -D 5
          bind -r K resize-pane -U 5
          bind -r L resize-pane -R 5

          # Rename pane title
          bind t command-prompt -p "Pane title:" "select-pane -T '%%'"

          # Enhanced tree view showing windows with pane counts and titles
          bind w choose-tree -Zw -F "#{window_name} (#{window_panes} panes)#{?pane_title, - #{pane_title},}"

          # Full tree view with all sessions, windows, and panes
          bind W choose-tree -Z

          # -------------------------------------------------------------------
          # Copy Mode (Vi-style)
          # -------------------------------------------------------------------
          bind-key -T copy-mode-vi v send -X begin-selection
          bind-key -T copy-mode-vi V send -X select-line
          bind-key -T copy-mode-vi C-v send -X rectangle-toggle

          # macOS clipboard integration
          if-shell "uname | grep -q Darwin" {
            bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
            bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"
          }

          # Enter copy mode with Prefix + Enter
          bind Enter copy-mode

          # -------------------------------------------------------------------
          # Status Bar (Catppuccin v2 modules)
          # -------------------------------------------------------------------
          # The catppuccin plugin is sourced before this block (see plugins
          # list), so @catppuccin_status_* modules and @thm_* palette vars are
          # already defined, and the plugin has already set status-style.
          set -g status-position bottom
          set -g status-interval 15

          set -g status-left-length 100
          set -g status-right-length 100

          # Left: session module
          set -g status-left "#{E:@catppuccin_status_session}"

          # Right: devpod session count (custom) + directory, host, clock.
          # devpod-status.sh emits its own #[fg=...] colours, so reset to the
          # palette afterward before the catppuccin modules render.
          set -g status-right "#(~/.local/bin/devpod-status.sh)"
          set -ga status-right "#[fg=#{@thm_fg},bg=#{@thm_bg}]"
          set -gaF status-right "#{E:@catppuccin_status_directory}"
          set -gaF status-right "#{E:@catppuccin_status_host}"
          set -gaF status-right "#{E:@catppuccin_status_date_time}"

          # Pane borders: keep per-pane gitmux (critical for worktree workflows)
          set -g pane-border-status top
          set -gF pane-border-style "fg=#{@thm_surface_0}"
          set -gF pane-active-border-style "fg=#{@thm_blue}"
          set -gF pane-border-format "#[fg=#{@thm_surface_2}]#P: #{pane_title} #(env -u DIRENV_DIR -u DIRENV_WATCHES gitmux -cfg ~/.gitmux.conf '#{pane_current_path}')"

          # -------------------------------------------------------------------
          # Popup Windows
          # -------------------------------------------------------------------
          bind ! display-popup -E -w 60% -h 75%

          bind m command-prompt -p "New session name:" "new-session -s '%%' -c '#{pane_current_path}'"

          if-shell "command -v fzf" {
            bind ` display-popup -E -w 60% -h 50% "tmux list-sessions | fzf --reverse --header='Select session:' | cut -d: -f1 | xargs tmux switch-client -t"
          }

          if-shell "command -v fzf" {
            bind X display-popup -E "tmux list-sessions -F '#{?session_attached,,#{session_name}}' | fzf --reverse | xargs -I {} tmux kill-session -t {}"
          }

          if-shell "command -v lazygit" {
            bind g display-popup -E -w 80% -h 80% "lazygit"
          }

          # -------------------------------------------------------------------
          # Plugin Settings
          # -------------------------------------------------------------------
          set -g @resurrect-capture-pane-contents 'on'
          set -g @resurrect-processes 'ssh'
          set -g @continuum-restore 'on'
          set -g @continuum-save-interval '60'
          # Catppuccin options moved to the plugin's extraConfig (must precede
          # the plugin's run-shell). See the plugins list above.
        ''
        + lib.optionalString config.dev-config.tmux.devpodConnect.enable ''

          # -------------------------------------------------------------------
          # DevPod Integration (Tailscale SSH sessions)
          # -------------------------------------------------------------------
          # Uses fzf-tmux -p for popup (creates its own tmux popup)
          # Note: Cannot use run-shell -b because fzf-tmux needs TTY context
          # Scripts are symlinked to ~/.local/bin/ by home-manager
          if-shell "command -v tailscale || [ -x /Applications/Tailscale.app/Contents/MacOS/Tailscale ]" {
            bind D run-shell "$HOME/.local/bin/devpod-connect.sh"
          }

          # Single mutagen entry point: start sync whenever a devpod_* session is
          # created (by either devpod-connect.sh or devpod-bootstrap.sh). The
          # hook script no-ops for non-devpod sessions and when sync is already
          # running, so it is safe to fire on every session.
          set-hook -g session-created 'run-shell "$HOME/.local/bin/devpod-mutagen-hook.sh #{hook_session_name}"'

          # Bootstrap: auto-create devpod sessions for online DevPods on server start
          # Run synchronously so sessions are ready before user interaction
          run-shell "bash $HOME/.local/bin/devpod-bootstrap.sh"
        '';
    };

    # Symlink gitmux configuration if source is provided
    home.file.".gitmux.conf" = lib.mkIf (config.dev-config.tmux.gitmuxConfigSource != null) {
      source = config.dev-config.tmux.gitmuxConfigSource;
    };

    # DevPod integration scripts (symlinked to ~/.local/bin/)
    home.file.".local/bin/devpod-connect.sh" =
      lib.mkIf (
        config.dev-config.tmux.devpodConnect.enable
        && config.dev-config.tmux.devpodConnect.connectScriptSource != null
      ) {
        source = config.dev-config.tmux.devpodConnect.connectScriptSource;
        executable = true;
      };

    home.file.".local/bin/devpod-status.sh" =
      lib.mkIf (
        config.dev-config.tmux.devpodConnect.enable
        && config.dev-config.tmux.devpodConnect.statusScriptSource != null
      ) {
        source = config.dev-config.tmux.devpodConnect.statusScriptSource;
        executable = true;
      };

    home.file.".local/bin/devpod-mutagen-hook.sh" =
      lib.mkIf (
        config.dev-config.tmux.devpodConnect.enable
        && config.dev-config.tmux.devpodConnect.mutagenHookScriptSource != null
      ) {
        source = config.dev-config.tmux.devpodConnect.mutagenHookScriptSource;
        executable = true;
      };

    home.file.".local/bin/devpod-bootstrap.sh" =
      lib.mkIf (
        config.dev-config.tmux.devpodConnect.enable
        && config.dev-config.tmux.devpodConnect.bootstrapScriptSource != null
      ) {
        source = config.dev-config.tmux.devpodConnect.bootstrapScriptSource;
        executable = true;
      };
  };
}
