git:
    github_token: ENC[AES256_GCM,data:TmzLEaekaVAt90idDUjqemhHIvLK6lYo5IZ4r5rm71+uYwvep+A2bA==,iv:f3anrsYf2IfmKG+l3anI217UyeBsZ5VfHVMxDjojJaU=,tag:bOgZw2WfHWY2xv4bNxhQZQ==,type:str]
op:
    service_account_token: ENC[AES256_GCM,data:uMaZ9CyXq4LWXUyM4uTHCaYLG2RHaEjpH1s38EBF7J/03vDmHHfBnl1UCDRdLeMdoUKopmW0oAMk0xAzdrzHgZlz8hIN0epsYJJw6VgWUdwu2LxmwjSh44ngByUtWAQ1CIB6iC4S8QvKXa1ZN+SD84qOBuMDd0wkpQG3AXNf8y+c2uBcBkp3+fmmk8cQqWQvTAUJBWH9iUcdB8CutwO0Lsn4F+N0XCbfg82YHF8bNnsymNUz00oCNciOshVlLkY+fqGhIzxV5stRAspuBRIwLSxfClC3BFUXWCCn3zTdYDkZb0pwFet5vP1EwUX6L47ZtUjl65Xlu0WHogIXPIcAerIHe6Tm4m1/IcAVhs14/TGYf5xz+IHRTcN6W4wPZj6PtBQm04Cqge0XN+snmJsctoafucrMeM0agEXq/0ixVRxy6Y3WmMa8iBpdfYGRXeAjhYLuUCzo93zUHjemF+Q1Xdb/oMw3yhV4QKnDu1mka89+kvIpUklds/AwERGgONu+wxzSFN4eawq0jrW2RkR8b3TdXccT7voDTlHqqDwBedwR7ar0JQe9AiEYFyKbzK7GB7sJ+DrQHW4EoU5KDMrW4SpuPkpmU+gW8cVMdUMXkgKe1bceWq2BLgSU/y8dJlypVJCi3Tr5gypjro4ErmXkTJlw/eNGa5uO+5Bglz5S51+pvVgZ/WmlkRjPs9Gg97qpGUNvGPSzpUvHMQXILOUKzU/Ud1LOuWJS28ve3B3A6V0jEQqOjxyZJUi+OLhsLy09mQ4gDEQ1BLJ516ishIFhfOd1z73x4REEx22Sf3yqySMCW5riGW6MsJmGon+geAWwseAo0EQfyq4FkfkwQ5Q2yKSX3+buSpyrdQuQ9prsqToVhgFaCLIDdakO36upUXp4qxXb9GTgkfwHRLaS7PDV4caNug6xGQb8yD0ZcXHxgSpQPUY9nphJyVMwghoLGz5yWR8rv/Rn7Q7zEiMCuxrPflnkC2uaK7PbLrZHaI/FLIu0Pouyc4niO9Oj7ZYdLPb3BesryI/Lc8IdN9M30Pv3GfmdciPuxO1ubnMyPNkekejgl43GiT8TqeD27F5H6SmIj4dUTc0riToC/2PRo9iCMt7tlJnH89Wb25P4n0dAD6nytMB5,iv:F2uw1xpNXWspseyh8QDESfD5YDgAnpCulbWQaL4RI3o=,tag:XIpIJY5nnR8yqG3f74+BSw==,type:str]
linear:
    mcp_api_key: ENC[AES256_GCM,data:ZILzpWudQqQYJ+fGdc0+WGYBHkw26pzhJZRbzpHvMYgrahW3kQpV46Yoku0XkJpx,iv:3Zde1FdFjtsGkWasMzniQ9kkTq73mvGBvrturcRKUk4=,tag:YKq0/xXM1pKFiCGkIdgg4g==,type:str]
sops:
    age:
        - recipient: age1y2zrsu82k5fuglxsd7mkkgph682zxfxmzeuprge6sqe8fq8g8ajqcdg988
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSnp3MWtNcjRFUWNmYTk1
            TjhtTWNGbTVWOUFBa3RBV0JLM1BOZVdTTHh3CjdNcHlTbTB4b2ZyL0s0S1hhL3Vz
            M1k2M0pXRmVObDNNMEtoUmt1Q2JTeUkKLS0tIEJTdVB4ZTNQcVhZU093bVZ4MlBS
            N2M5ellIOHFwY00vNzUrV0NnTXVUTWMKeveSx5OKsENuMqDqEY5SUc1VBAv47qIJ
            KLU5Wh2HqHDHDc0MyY+8WkzdU9UkpPVRrz94G2Oz5OLBIYwTEBr/gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T01:31:33Z"
    mac: ENC[AES256_GCM,data:uoJSwBoYkKgnQOAIrTwxGi+Iln0bVm17uK9PqKU/nDhBbf4f9TvZXcdNq0SLsYim2hft04xw127w+HbS57s0wB4K6pbmzyH2UfTQco4goR/aeHev5FeLtxoPkdE8etwSgCECxDm3CoW519O9DDknrnBF5uSYOIPhDyuzdVaHPOI=,iv:4S+tKsUIwovJzFi8Md9ZWdn6g+dIWEbBQpyxD+lQIas=,tag:Um4HTamuz663pPNnqDIxGw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
